zoo: bin/zookeeper-server-start.sh config/zookeeper.properties

broker1: env KAFKA_OPTS="-Djava.security.auth.login.config=./kafka_server_jaas.conf" bin/kafka-server-start.sh config/server.1.properties

broker2: env KAFKA_OPTS="-Djava.security.auth.login.config=./kafka_server_jaas.conf" bin/kafka-server-start.sh config/server.2.properties

broker3: env KAFKA_OPTS="-Djava.security.auth.login.config=./kafka_server_jaas.conf" bin/kafka-server-start.sh config/server.3.properties
